name: NekoBoard
main: com.nekomc.nekoBoard.NekoBoard
version: 1.0.0
author: [TheRedMelonYT, TheDreps]
depend: [LeCorePlugin, Vault]
softdepend: [Multiverse-Core]
commands:
  update:
    description: asdkjf