name: NekoEco
main: me.thedreps.nekoEco.NekoEco
version: 1.0
author: TheDreps
website: www.nekomc.com
commands:
  balance:
    description: Shows the players balance.
    aliases: [bal, money]