name: NekoChat
main: me.thedreps.nekochat.NekoChat
version: 2.2.1
author: TheDreps
description: Manages chat events in NekoMC
dependancy: NekoCore
website: www.nekomc.com
commands:
  rules:
    description:  Shows the rules!
  nickname:
    description: Set a nickname!
    aliases: [nick]