name: NekoFundomentals
version: 1
authors: [TheDreps, TheRedMelon]
website: www.nekomc.com
main: com.nekomc.nekoFundamentals.NekoFundamentals
commands:
  gamemode:
    description: Change your gamemode.
    aliases: [gm, gmc, gms]
  suicide:
    description: kill yourself.
  kill:
    description: kills a player.
  heal:
    description: heal you, or others.
  fly:
    description: lets you fly/stops you from flying.
  feed:
    description: feeds you, or others.